controller_list:
- name: /arm_1/arm_controller
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
- name: /base_controller
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - youbot_base
#- name: /arm_1/gripper_controller #not setup yet
#  action_ns: gripper_command
#  type: GripperCommand
#  joints:
#    - gripper_finger_joint_l
#    - gripper_finger_joint_r